### ISSUE TITLE
可能是bug， 小程序内App.vue里是无法获取到this.$u的

### ISSUE THREAD

**Issue by Arya-DOTA** [gooking/uni-app-mall#3]
![image](https://user-images.githubusercontent.com/16175908/166882749-c2b7c2ab-ff3e-431e-8c38-31fd9a39c5ef.png)

![image](https://user-images.githubusercontent.com/16175908/166882952-7d1aa43d-eff2-466b-8bed-0ec1b0269da9.png)

**Comment by gooking** [comment]
可以的，测试没有问题
